apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: prod-

patches:
  - target:
      kind: Deployment
      name: prism-server
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
  - target:
      kind: Deployment
      name: prism-frontend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
