[agent]
id = "prism-all-in-one-node"
hub_url = "ws://127.0.0.1:65432/agent/connect"
token = "prism-secure-token-2026"

[[services]]
name = "mysql"
type = "systemd"

[[services]]
name = "postgresql"
type = "systemd"

[[services]]
name = "rabbitmq"
type = "systemd"

[[services]]
name = "caddy"
type = "systemd"

[[services]]
name = "nginx"
type = "systemd"

[[services]]
name = "minio"
type = "systemd"

[[services]]
name = "pm2"
type = "pm2"

[[services]]
name = "vsftpd"
type = "systemd"

[[services]]
name = "mongod"
type = "systemd"
