# Standard Systemd Services
[[services]]
name = "caddy"
type = "systemd"
service_name = "caddy"

[[services]]
name = "nginx"
type = "systemd"
service_name = "nginx"

[[services]]
name = "mysql"
type = "systemd"
service_name = "mysqld"

[[services]]
name = "postgresql"
type = "systemd"
service_name = "postgresql"

[[services]]
name = "rabbitmq"
type = "systemd"
service_name = "rabbitmq-server"

[[services]]
name = "mongodb"
type = "systemd"
service_name = "mongod"

# PM2 Service
[[services]]
name = "pm2"
type = "pm2"
