services = []

[server]
host = '0.0.0.0'
port = 65432
domain = 'example.com'
tls_enabled = false
tls_cert = '/etc/letsencrypt/live/example.com/fullchain.pem'
tls_key = '/etc/letsencrypt/live/example.com/privkey.pem'

[auth]
token = 'vX8GKv_SMHJplvXvL6__nuJjiA_HXj0aXINNK5sFgDo='
jwt_secret = 'm5OY_12Hk8AvKsigSBb0ZJfbqQfRIlhxUilZdGJKkqA='

[database]
path = './prism.db'

[valkey]
addr = 'localhost:6379'
password = ''
db = 0
