[server]
host = "0.0.0.0"
port = 65433
domain = "example.com"
tls_enabled = false # Set to true in production
tls_cert = "/etc/letsencrypt/live/example.com/fullchain.pem"
tls_key = "/etc/letsencrypt/live/example.com/privkey.pem"

[hub]
url = "ws://localhost:65432/agent/connect"
token = "secret-token"


[database]
path = "./data.db"

# Example: Custom or Standard Services
# [[services]]
# name = "minio"
# type = "systemd"
# service_name = "minio"

# [[services]]
# name = "garage"
# type = "systemd"
# service_name = "garage"

# [[services]]
# name = "sftpgo"
# type = "systemd"
# service_name = "sftpgo"

# [[services]]
# name = "seaweedfs"
# type = "systemd"
# service_name = "seaweedfs"
