[server]
host = ''
port = 0
domain = ''
tls_enabled = false
tls_cert = ''
tls_key = ''

[hub]
url = 'ws://192.168.122.230:65432/agent/connect'
token = 'replace_with_actual_token'

[database]
path = ''

[[services]]
name = 'mysql'
type = 'systemd'
service_name = 'mysql'
user_scope = false

[[services]]
name = 'caddy'
type = 'systemd'
service_name = 'caddy'
user_scope = false
