apiVersion: v1
kind: Service
metadata:
  name: prism-server
  namespace: prism
  labels:
    app.kubernetes.io/name: prism-server
    app.kubernetes.io/part-of: prism
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: prism-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prism-server-data
  namespace: prism
  labels:
    app.kubernetes.io/name: prism-server
    app.kubernetes.io/part-of: prism
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
