apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prism.server.fullname" . }}
  labels:
    {{- include "prism.server.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.server.secrets.jwtSecret | quote }}
  agent-token: {{ .Values.server.secrets.agentToken | quote }}
